name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - .github/workflows/composite_npm_build/**
      - biweekly/**
      - blog/**
      - docs/**
      - i18n/**
      - news/**
      - src/**
      - static/**
      - package.json
      - pnpm-lock.yaml
      - docusaurus.config.js
      - postcss.config.cjs
      - tailwind.config.cjs
      - uno.config.ts
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    environment: cloudflare-pages
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: PNPM Build
        uses: ./.github/workflows/composite_npm_build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./build --project-name=${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }}
          # Optional: Enable this if you want to have GitHub Deployments triggered
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
